export const serverLink = 'http://localhost:8080'

export default {

    BUY_PRODUCT: 'BUY_PRODUCT',
    VIEW_PRODUCT: 'VIEW_PRODUCT',
    REVIEW_PRODUCT: 'REVIEW_PRODUCT',
    COMPLAINT_PRODUCT: 'COMPLAINT_PRODUCT',
    COMPLAINT_FEEDBACK: 'COMPLAINT_FEEDBACK'
}